@startuml TaskFlow

start

:Client;

if ("¿Is the client registered?") then (No)
    :Register;
    if ("¿Duplicate Data?") then (Yes)
        :Show error 409;
        stop
    else
        :Save user data in the database;
        :Generate code to validate email;
        stop
    endif
else
    :Verify Email;
    if ("Email Verified?") then (Yes)
        :Login;
        if ("Are credentials valid?") then (Yes)
            :Access to profile;

            if ("Has Roles?") then (Yes)
                if ("Admin?") then (Yes)
                    if ("Total Access") then (Yes)
                        :CRUD user;
                        :Give Access Level;
                        :CRUD project;
                        :CRUD task;
                    endif
                elseif ("Creator?") then (Yes)
                    :List of Users;
                    :CRUD project;
                    :Give Access Level;
                    :CRUD task;
                elseif ("Basic?") then (Yes)
                    :Create Project;
                    if ("Has Access Level?") then (Yes)
                        if ("OWNER") then (Yes)
                            :Create Project;
                            :Get Project by ID;
                            :Update Project;
                            :CRUD task;
                        elseif ("MAINTAINER") then (Yes)
                            :Create Project;
                            :Update Project;
                            :CRUD task;
                        elseif ("DEVELOPER") then (Yes)
                            :CRUD task;
                        endif
                    else
                        :Error 401 Unauthorized;
                        stop
                    endif
                endif

                :Progress Task;
                if ("Task Status") then (CREATED)
                    :Task Created;
                elseif ("IN_PROGRESS")
                    :Task In Progress;
                elseif ("FINISH")
                    :Task Finished;
                endif

            else
                :Error 401 Unauthorized;
                stop
            endif

            stop
        else
            :Show error;
            :Error 401 Unauthorized;
            :Error 404 User not found;
            stop
        endif
    else
        :Ask to verify email again;
        stop
    endif
endif

@enduml
